"""Validate the response contract before showing claims as sourced answers."""

from dataclasses import dataclass
import json
import re

from documents import SourceChunk


@dataclass(frozen=True)
class AnswerResult:
    answer: str
    status: str
    sources: tuple[SourceChunk, ...] = ()
    retrieval_query: str = ""
    candidates: tuple[SourceChunk, ...] = ()


def parse_object(raw):
    raw = raw.strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
    value = json.loads(raw)
    if not isinstance(value, dict):
        raise ValueError("Expected an object")
    return value


def validate_answer(raw, sources, retrieval_query):
    def reject():
        return AnswerResult("回答的格式或原文依据未通过检查，暂不展示为可靠答案。请重试或查看候选原文。",
                            "unverified", retrieval_query=retrieval_query, candidates=tuple(sources))
    try:
        value = parse_object(raw)
        if type(value.get("answerable")) is not bool:
            return reject()
        if not value["answerable"]:
            return AnswerResult("当前检索到的原文不足以回答这个问题。可以补充资料，或换一种更明确的问法。",
                                "insufficient", retrieval_query=retrieval_query, candidates=tuple(sources))
        claims = value.get("claims")
        if not isinstance(claims, list) or not 1 <= len(claims) <= 6:
            return reject()
        used, sentences = [], []
        for claim in claims:
            if not isinstance(claim, dict):
                return reject()
            text, quote, number = claim.get("text"), claim.get("quote"), claim.get("source_id")
            if not isinstance(text, str) or not text.strip() or len(text) > 1000:
                return reject()
            if type(number) is not int or not 1 <= number <= len(sources):
                return reject()
            if not isinstance(quote, str):
                return reject()
            normalized = re.sub(r"\s+", "", quote)
            original = re.sub(r"\s+", "", sources[number - 1].text)
            if len(normalized) < min(6, len(original)) or normalized not in original:
                return reject()
            # Citation labels are generated by code, never accepted from the model.
            if re.search(r"\[\s*来源", text):
                return reject()
            if number not in used:
                used.append(number)
            sentences.append(f"{text.strip()} [来源{used.index(number) + 1}]")
        return AnswerResult("\n\n".join(sentences), "answered",
                            tuple(sources[i - 1] for i in used), retrieval_query)
    except (ValueError, TypeError, AttributeError):
        return reject()
