[theme]
base = "light"
primaryColor = "#315FEA"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17243B"
font = "sans serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
